---
#- name: apply some rogue changes using ansible
- hosts: eosnodes
  gather_facts: False
  connection: local
  tasks:
    - name: show the EOS version
      eos_command:
        commands: 'show version'

    - name: Remove vlans on switchports
      eos_l2_interface:
        authorize: yes
        aggregate:
        - { name: port-channel2, mode: trunk, native_vlan: 5}
        state: absent

    - name: nuke some vlans
      eos_vlan:
        authorize: yes
        timeout: 30
        aggregate:
        - vlan_id: 3000
        - {vlan_id: 3002, name: vlan-3002}
        - {vlan_id: 3003, name: vlan-3003}
        - {vlan_id: 4000, name: vlan-4000}
        - {vlan_id: 4001, name: vlan-4001}
        - {vlan_id: 4002, name: vlan-4002}
        - {vlan_id: 4003, name: vlan-4003}
        - {vlan_id: 4004, name: vlan-4004}
        - {vlan_id: 4005, name: vlan-4005}
        state: absent

    - name: remove the login banner
      eos_banner:
        authorize: yes
        banner: login
        state: absent
